spring.application.name=gateway

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

#Para que no se problemas con la linea a anterior
spring.cloud.config.import-check.enabled=false
spring.config.import=classpath:config/gateway.yaml

#Permite conocer los endpoints
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE

spring.output.ansi.enabled=always