server.port=1111
spring.application.name=eureka

# Solo tiene sentido si arranco antes el servidor de configuraciones
# spring.cloud.config.uri=http://localhost:2222
# spring.config.import=optional:configserver:

eureka.instance.hostname=localhost
spring.output.ansi.enabled=ALWAYS
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false