server:
  port: 8081

spring:
  cloud: 
    gateway: 
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webflux:
          routes:
            - id: evento
              uri: lb://evento/
              predicates:
                - Path=/eventos/**
            - id: compras
              uri: lb://compras/
              predicates:
                - Path=/compras/**