server:
  port: 8081

spring:
  cloud: 
    gateway: 
      server:
        webflux:
          routes:
            - id: evento
              uri: lb://evento/
              predicates:
                - Path=/eventos/**
            - id: compras
              uri: lb://compras/
              predicates:
                - Path=/compras/**