server:
  port: 8081

spring:
  cloud: 
   gateway: 
    routes:
      - id: evento
        uri: lb://eventos/
        predicates:
          - Path=/eventos/**
      - id: compras
        uri: lb://compras/
        predicates:
          - Path=/compras/**      
